users/urls.py
#定义users的URL模式
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
	#登录页面
	path('', include('django.contrib.auth.urls')),
	#注册页面
	path('register', views.register, name='register'),
]

white_dreams/urls.py
#定义white_dreams的URL模式
from django.urls import path

from . import views

app_name = 'white_dreams'
urlpatterns = [
	#主页
	path('', views.index, name='index'),
	#所有主题的页面
	path('titles/', views.titles, name='titles'),
	#特定主题的页面
	path('titles/<int:title_id>/', views.title, name='title'),
	#添加主题的页面
	path('new_title/', views.new_title, name='new_title'),
	#添加内容的页面
	path('new_write/<int:title_id>/', views.new_write, name='new_write'),
]	

yunrj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('white_dreams.urls')), 
]

users/models.py
from django.db import models

# Create your models here.

white_dreams/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Title(models.Model):
	'''用户记录的标题'''
	text = models.CharField(max_length=50)
	date_added = models.DateTimeField(auto_now_add=True)

	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		'''返回模型的字符串表示'''
		return self.text
		
class Write(models.Model):
	'''用户记录的内容'''
	title = models.ForeignKey(Title, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		'''返回模型的字符串表示'''
		return f'{self.text[:50]}...'

white_dreams/forms.py
from django import forms

from .models import Title,Write

class TitleForm(forms.ModelForm):
	class Meta:
		model = Title
		fields = ['text']
		labels = {'text': ''}

class WriteForm(forms.ModelForm):
	class Meta:
		model = Write
		fields = ['text']
		labels = {'text': ''}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here

def register(request):
	'''注册用户'''
	if request.method != 'POST':
		#显示空的注册表单
		form = UserCreationForm()
	else:
		#处理填写好的表单
		form = UserCreationForm(data=request.POST)
		if form.is_valid():
			new_user = form.save()
			#让用户自动登入 在重定向到主页
			login(request, new_user)
			return redirect('white_dreams:index')

	#显示空表单或指出表单无效
	context = {'form': form}
	return render(request, 'registration/register.html', context)

white_dreams/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Title, Write
from .forms import TitleForm, WriteForm

# Create your views here.

def index(request):
	'''主页'''
	return render(request, 'white_dreams/index.html')

@login_required
def titles(request):
	'''所有主题的页面'''
	titles = Title.objects.filter(owner=request.user).order_by('date_added')
	context = {'titles': titles}
	return render(request, 'white_dreams/titles.html', context)

@login_required
def title(request, title_id):
	'''特定主题的页面'''
	title = Title.objects.get(id=title_id)
	#确认请求的主题属于当前用户
	if title.owner != request.user:
		raise Http404

	writes = title.write_set.order_by('-date_added')
	context = {'title': title, 'writes': writes}
	return render(request, 'white_dreams/title.html', context)

@login_required
def new_title(request):
	'''添加主题的页面'''
	if request.method != 'POST':
		#未提交数据 创建一个新表单
		form = TitleForm()
	else:
		#POST提交的数据 对数据进行处理
		form = TitleForm(data=request.POST)
		if form.is_valid():
			new_title = form.save(commit=False)
			new_title.owner = request.user
			new_title.save()
			return redirect('white_dreams:titles')

	#显示空表单或指出表单数据无效
	context = {'form': form}
	return render(request, 'white_dreams/new_title.html', context)

@login_required
def new_write(request, title_id):
	'''添加内容的页面'''
	title = Title.objects.get(id=title_id)

	if request.method != 'POST':
		#未提交数据 创建新表单
		form = WriteForm()
	else:
		#POST交的数据 对数据进行处理
		form = WriteForm(data=request.POST)
		if form.is_valid():
			new_write = form.save(commit=False)
			new_write.title = title
			new_write.save()
			return redirect('white_dreams:title', title_id=title_id)

	#显示空表单或指出表单数据无效
	context = {'title': title, 'form': form}
	return render(request, 'white_dreams/new_write.html', context)	

white_dreams/templates/white_dreams/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, 
	shrink-to-fit=no">
	<title>云日记</title>

	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}

</head>
<body>

	<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
		
		<a class="navbar-brand" href="{% url 'white_dreams:index' %}">主页</a>

		<button class="navbar-toggler" type="button" data-toggle="collapse"
		data-target="#navbarCollapse" aria-controls="navbarCollapse"
		aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'white_dreams:titles'%}">主题</a>
				</li>
			</ul>
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
				<li class="nav-item">
					<span class="navbar-text">你好，{{ user.username }}</span>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:logout' %}">退出登录</a>
				</li>				
				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:login' %}">登录</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:register' %}">注册</a>
				</li>
				{% endif %}
			</ul>
		</div>
	</nav>

	<main role="main" class="container">
		<div class="pb-2 mb-4 border-bottom">
			{% block page_header %}{% endblock page_header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</main>

</body>

</html>

white_dreams/templates/white_dreams/index.html
{% extends 'white_dreams/base.html' %}

{% block page_header %}
<div class="jumbotron">
	<h1 class="display-3">欢迎来到云日记平台</h1>

	<p class="read">
		在这，你可以记录你的生活，并添加关于你生活的主题。
	</p>
	<p class="read">你经历了关于某个主题的新东西时，
		都可以写下相关内容，总结你的想法或规划。
	</p>

	{% if user.is_authenticated %}
	<a class="btn btn-lg btn-primary" href="{% url 'white_dreams:titles' %}"
	role="button">主题 &raquo</a>
	{% else %}
	<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
	role="button">注册 &raquo</a>
	{% endif %}
</div>
{% endblock page_header %}

white_dreams/templates/white_dreams/new_title.html
{% extends 'white_dreams/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
<h2>添加主题</h2>
{% endblock page_header %}

{% block content %}
<p>添加主题:</p>

<form action="{% url 'white_dreams:new_title' %}" method="POST" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}

	{% buttons %}
	<button name="submit" class="btn btn-primary">添加</button>
	{% endbuttons %}

	<input type="hidden" name="next"
	value="{% url 'white_dreams:titles' %}" />

</form>

{% endblock content %}

white_dreams/templates/white_dreams/new_write.html
{% extends 'white_dreams/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
<h2>添加内容</h2>
{% endblock page_header %}

{% block content %}
<h5><a href="{% url 'white_dreams:title' title.id %}">回到{{ title }}</a></h5>
<p>添加内容:</p>

<form action="{% url 'white_dreams:new_write' title.id %}" method="POST" class="form">
	{% csrf_token %}
	{% bootstrap_form form %}

	{% buttons %}
	<button name="submit" class="btn btn-primary">添加</button>
	{% endbuttons %}

	<input type="hidden" name="next"
	value="{% url 'white_dreams:title' title.id %}" />

</form>

{% endblock content %}

white_dreams/templates/white_dreams/title.html
{% extends 'white_dreams/base.html' %}

{% block page_header %}
<h3>{{ title }}</h3>
{% endblock page_header %}

{% block content %}

<p>
	<a href="{% url 'white_dreams:new_write' title.id %}">添加内容</a>
</p>

{% for write in writes %}
<div class="card mb-3">
	<h4 class="card-header">
		{{ write.date_added|date:'Y.M.d H:i' }}
	</h4>
	<div class="card-body">
		{{ write.text|linebreaks }}		
	</div>
</div>

{% empty %}
<p>当前主题还未添加内容</p>
{% endfor %}

{% endblock content %}

white_dreams/templates/white_dreams/titles.html
{% extends 'white_dreams/base.html' %}

{% block page_header %}
<h1>主题</h1>
{% endblock page_header %}

{% block content %}

<ul>
	{% for title in titles %}
	<li><h3>
		<a href="{% url 'white_dreams:title' title.id %}">{{ title }}</a>
	</h3></li>
	{% empty %}
	<li><h4>你还未添加任何主题</h4></li>
	{% endfor %}
</ul>

<h5><a href="{% url 'white_dreams:new_title' %}">添加主题</a></h5>

{% endblock content %}